services:
  doumi-server:
    build:
      context: ./anno_doumi/server
    ports:
      - "8080:8080"
    volumes:
      - ./anno_doumi/server:/app

  doumi-agent:
    build:
      context: ./anno_doumi/agent
    volumes:
      - ./anno_doumi/agent:/app
      - ~/.cache/whisper:/root/.cache/whisper
    depends_on:
      - doumi-server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
#    devices:  Not for Mac OS
#      - /dev/snd:/dev/snd  # Not for Mac OS
